name: Atlas CI
on:
  pull_request:
  
jobs:
  lint:
    services:
      # Spin up a mysql:8.0.29 container to be used as the dev-database for analysis.
      mysql:
        image: mysql:8.0.29
        env:
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_DATABASE: test
        ports:
          - "3307:3306"
        options: >-
          --health-cmd "mysqladmin ping -ppass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 0 # Mandatory unless "latest" is set below.
      - uses: ariga/atlas-action@master
        with:
          dir: 'ent/migrate/migrations'
          dir-format: atlas
          dev-url: mysql://root:pass@localhost:3307/test
          ariga-token: ${{ secrets.ARIGA_TOKEN }}_invalid
          ariga-url: https://ci.ariga.dev/


